### PR TITLE
[DEV-55] Data Explorer: New Neo4j model

### PR DESCRIPTION
**Pull request by bnordli**
This change is [Reviewable](https://reviewable.io/reviews/exabel/api/84)

### CODE REVIEW

**Review by grotmol — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/84)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @bnordli)

___
*[exabel/api/data/v1/entity_messages.proto, line 26 at r1](https://reviewable.io/reviews/exabel/api/84#-MpBpJyhCyATfr5br74y:-MpBpJyi1ntF_gI22Wf_:bctj3w4) ([raw file](https://github.com/exabel/api/blob/528f64732919cda4a3e089eefe3ce77ee8386709/exabel/api/data/v1/entity_messages.proto#L26)):*
> ```protobuf
>   // Output only. Whether this resource is read only.
>   bool read_only = 4;
>   // Whether this is an intermediate entity type, not normally searchable or assignable to signals.
> ```

What is meant by "assignable to signals"?

We do have time series for the intermediate entities (in fact, that's typically why they are there).

I'm afraid the name "intermediate" may be confusing to some users. If you have a data model with three levels, let's say company, brand and product, might it be that people would think that brand is an "intermediate" entity type, because it's not a root node and not a leaf in the tree structure?

What could be other possible names? "transparent" because we don't show it, it only connects to other entities? "connecting"?

**Review by bnordli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/84)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @oyvindwe)

___
*[exabel/api/data/v1/entity_messages.proto, line 26 at r1](https://reviewable.io/reviews/exabel/api/84#-MpBpJyhCyATfr5br74y:-MpBuU1Z6Pu1AoAyxT4I:b-ioxipb) ([raw file](https://github.com/exabel/api/blob/528f64732919cda4a3e089eefe3ce77ee8386709/exabel/api/data/v1/entity_messages.proto#L26)):*
<details><summary><i>Previously, grotmol (Øyvind Grotmol) wrote…</i></summary><blockquote>

What is meant by "assignable to signals"?

We do have time series for the intermediate entities (in fact, that's typically why they are there).

I'm afraid the name "intermediate" may be confusing to some users. If you have a data model with three levels, let's say company, brand and product, might it be that people would think that brand is an "intermediate" entity type, because it's not a root node and not a leaf in the tree structure?

What could be other possible names? "transparent" because we don't show it, it only connects to other entities? "connecting"?
</blockquote></details>

That was a misunderstanding on my part, I'll delete the signal reference. @oyvindwe , what do you suggest we name this field?

**Review by oyvindwe — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/84)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @bnordli and @grotmol)

___
*[exabel/api/data/v1/entity_messages.proto, line 26 at r1](https://reviewable.io/reviews/exabel/api/84#-MpBpJyhCyATfr5br74y:-MpCjwT69si0UEPPqf-f:b-eju39s) ([raw file](https://github.com/exabel/api/blob/528f64732919cda4a3e089eefe3ce77ee8386709/exabel/api/data/v1/entity_messages.proto#L26)):*
<details><summary><i>Previously, bnordli (Børge Nordli) wrote…</i></summary><blockquote>

That was a misunderstanding on my part, I'll delete the signal reference. @oyvindwe , what do you suggest we name this field?
</blockquote></details>

If we have time series for an "intermediate" entity (aggregations?), then it should probably show up in the Data Explorer and be searchable?

Regarding naming, I find it difficult to come up with another name. We call these nodes "intermediate entities for signals related to multiple entities" in the data loading how-to guide.
___
*[exabel/api/data/v1/relationship_messages.proto, line 27 at r1](https://reviewable.io/reviews/exabel/api/84#-MpCkaLe9d5qXwq3q0PB:-MpCkaLe9d5qXwq3q0PC:b90synn) ([raw file](https://github.com/exabel/api/blob/528f64732919cda4a3e089eefe3ce77ee8386709/exabel/api/data/v1/relationship_messages.proto#L27)):*
> ```protobuf
>   // Whether this relationship type specifices an "ownership" in the data set model. The
>   // relationship direction goes from the owner to the sub entity.
>   bool is_ownership = 4;
> ```

I'm not too happy with this property name, but I don't have any better suggestions either…

**Review by bnordli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/84)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @bnordli and @grotmol)

___
*[exabel/api/data/v1/entity_messages.proto, line 26 at r1](https://reviewable.io/reviews/exabel/api/84#-MpBpJyhCyATfr5br74y:-MpLHddU9F8H3nO8Vyw3:bswkv88) ([raw file](https://github.com/exabel/api/blob/528f64732919cda4a3e089eefe3ce77ee8386709/exabel/api/data/v1/entity_messages.proto#L26)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

If we have time series for an "intermediate" entity (aggregations?), then it should probably show up in the Data Explorer and be searchable?

Regarding naming, I find it difficult to come up with another name. We call these nodes "intermediate entities for signals related to multiple entities" in the data loading how-to guide.
</blockquote></details>

We haven't reached a conclusion on the names. Can you two do a quick chat in the office to figure this out?

**Comment by grotmol** [comment]
___
*[exabel/api/data/v1/entity_messages.proto, line 26 at r1](https://reviewable.io/reviews/exabel/api/84#-MpBpJyhCyATfr5br74y:-MpLJLKYDX6H7PjrlQ3i:beektgo) ([raw file](https://github.com/exabel/api/blob/528f64732919cda4a3e089eefe3ce77ee8386709/exabel/api/data/v1/entity_messages.proto#L26)):*
<details><summary><i>Previously, bnordli (Børge Nordli) wrote…</i></summary><blockquote>

We haven't reached a conclusion on the names. Can you two do a quick chat in the office to figure this out?
</blockquote></details>

My vote now goes to the field name `associative`. It makes sense because this entity is just the association of several other entities. More importantly, this is what Wikipedia calls these entities, so we can always refer to that:
https://en.wikipedia.org/wiki/Associative_entity
We may even want to include the link to the Wikipedia article to explain what we mean.

**Review by grotmol — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/84)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @bnordli and @oyvindwe)

___
*[exabel/api/data/v1/entity_messages.proto, line 26 at r1](https://reviewable.io/reviews/exabel/api/84#-MpBpJyhCyATfr5br74y:-MpLda_rA7ufkd1Y4iku:b-jerjnr) ([raw file](https://github.com/exabel/api/blob/528f64732919cda4a3e089eefe3ce77ee8386709/exabel/api/data/v1/entity_messages.proto#L26)):*
<details><summary><i>Previously, grotmol (Øyvind Grotmol) wrote…</i></summary><blockquote>

My vote now goes to the field name `associative`. It makes sense because this entity is just the association of several other entities. More importantly, this is what Wikipedia calls these entities, so we can always refer to that:
https://en.wikipedia.org/wiki/Associative_entity
We may even want to include the link to the Wikipedia article to explain what we mean.
</blockquote></details>

Øyvind W agrees (at least doesn't disagree), so let's move forward with `associative`!

**Review by oyvindwe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/84)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @bnordli and @grotmol)

___
*[exabel/api/data/v1/entity_messages.proto, line 26 at r1](https://reviewable.io/reviews/exabel/api/84#-MpBpJyhCyATfr5br74y:-MpLf1LG9BkNcA8nUz_U:b4c9lyr) ([raw file](https://github.com/exabel/api/blob/528f64732919cda4a3e089eefe3ce77ee8386709/exabel/api/data/v1/entity_messages.proto#L26)):*
<details><summary><i>Previously, grotmol (Øyvind Grotmol) wrote…</i></summary><blockquote>

Øyvind W agrees (at least doesn't disagree), so let's move forward with `associative`!
</blockquote></details>

:thumbsup:

**Review by bnordli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/84)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @bnordli and @grotmol)

___
*[exabel/api/data/v1/entity_messages.proto, line 26 at r1](https://reviewable.io/reviews/exabel/api/84#-MpBpJyhCyATfr5br74y:-MpLqg7q2GcwwPai6-ZK:b-896fja) ([raw file](https://github.com/exabel/api/blob/528f64732919cda4a3e089eefe3ce77ee8386709/exabel/api/data/v1/entity_messages.proto#L26)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Done!

**Review by grotmol — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/84#-:-MpLscimBq5BtjJkJj8C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
