### PR TITLE
Exabel branding

### PR DESCRIPTION
**Pull request by oyvindwe**
This change is [Reviewable](https://reviewable.io/reviews/exabel/api/80)

### CODE REVIEW

**Review by bnordli — CHANGES_REQUESTED** [review]
> Reviewed 36 of 36 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/80)* status: all files reviewed, 1 unresolved discussion (waiting on @oyvindwe)

___
*[exabel/api/data/doc/timeseries.rst, line 135 at r2](https://reviewable.io/reviews/exabel/api/80#-MhZ-yRWC8LsImUOTp46:-MhZ-yRX34yv9fCUpzhP:b-twqble) ([raw file](https://github.com/exabel/api/blob/c4402e770864e88c939d122b67afe6e073f8de5c/exabel/api/data/doc/timeseries.rst#L135)):*
> ```reStructuredText
> 
> **Note** Time series points are stored with second resolution, however the Exabel Platform only supports processing
> time series with daily or higher resolution. Time stamps must be normalised to **midnight UTC** (```00:00:00Z``).
> ```

Was this intentional?

**Review by bnordli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/80)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[exabel/api/data/doc/timeseries.rst, line 135 at r2](https://reviewable.io/reviews/exabel/api/80#-MhZ-yRWC8LsImUOTp46:-MhZ0EvI0CRNXeFDQdH2:bbsdjng) ([raw file](https://github.com/exabel/api/blob/c4402e770864e88c939d122b67afe6e073f8de5c/exabel/api/data/doc/timeseries.rst#L135)):*
<details><summary><i>Previously, bnordli (Børge Nordli) wrote…</i></summary><blockquote>

Was this intentional?
</blockquote></details>

Looks like it works!

**Review by oyvindwe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/80)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[exabel/api/data/doc/timeseries.rst, line 135 at r2](https://reviewable.io/reviews/exabel/api/80#-MhZ-yRWC8LsImUOTp46:-MhZCg9D2mQu42nljj8Z:b1q1hdg) ([raw file](https://github.com/exabel/api/blob/c4402e770864e88c939d122b67afe6e073f8de5c/exabel/api/data/doc/timeseries.rst#L135)):*
<details><summary><i>Previously, bnordli (Børge Nordli) wrote…</i></summary><blockquote>

Looks like it works!
</blockquote></details>

Yes, it was a formatting fix! Should have been a separate commit.

**Review by bnordli — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/80)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
