### PR TITLE
Add links to github and developer portal

### PR DESCRIPTION
**Pull request by hallarak**
This change is [Reviewable](https://reviewable.io/reviews/exabel/api/61)

### CODE REVIEW

**Review by oyvindwe — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/61)* status: all files reviewed, 3 unresolved discussions (waiting on @hallarak)

___
*[exabel/api/data/doc/access.rst, line 6 at r1](https://reviewable.io/reviews/exabel/api/61#-MdMnTvY4j86h7fqHrxc:-MdMnTvY4j86h7fqHrxd:bf4tmak) ([raw file](https://github.com/exabel/api/blob/7fd120140e6c61a1550e6adb219cd3a9b4b67d28/exabel/api/data/doc/access.rst#L6)):*
> ```reStructuredText
> To access the Data API, you need an API key provided by Exabel.
> 
> You can access the Data API either directly with REST or by using the Exabel
> ```

"with REST" -> "by using gRPC or REST, "
___
*[exabel/api/data/doc/access.rst, line 9 at r1](https://reviewable.io/reviews/exabel/api/61#-MdMnbMa7hbBJ195_09O:-MdMnbMa7hbBJ195_09P:b-xmft4i) ([raw file](https://github.com/exabel/api/blob/7fd120140e6c61a1550e6adb219cd3a9b4b67d28/exabel/api/data/doc/access.rst#L9)):*
> ```reStructuredText
> Python SDK: https://pypi.org/project/exabel-data-sdk/
> 
> The Data API service definitions can be found here: https://github.com/Exabel/api.
> ```

Include full URL to Data API https://github.com/Exabel/api/tree/master/exabel/api/data/v1
___
*[exabel/api/data/doc/access.rst, line 11 at r1](https://reviewable.io/reviews/exabel/api/61#-MdMo1ic0W7zBIMAct95:-MdMo1ic0W7zBIMAct96:b-1hi5n3) ([raw file](https://github.com/exabel/api/blob/7fd120140e6c61a1550e6adb219cd3a9b4b67d28/exabel/api/data/doc/access.rst#L11)):*
> ```reStructuredText
> The Data API service definitions can be found here: https://github.com/Exabel/api.
> 
> API developer reference documentation can be found here:
> ```

"For API reference documentation of the REST API, please see <section> in this guide. Reference documentation for gRPC can be found here: …"


 Is it possible to make a supersection "REST API" (or similar) for the pages entities, relationships, signals, and timeseries?

**Review by hallarak — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/61)* status: all files reviewed, 3 unresolved discussions (waiting on @oyvindwe)

___
*[exabel/api/data/doc/access.rst, line 6 at r1](https://reviewable.io/reviews/exabel/api/61#-MdMnTvY4j86h7fqHrxc:-MdMwJy36B9VOgGCztP3:b-896fix) ([raw file](https://github.com/exabel/api/blob/7fd120140e6c61a1550e6adb219cd3a9b4b67d28/exabel/api/data/doc/access.rst#L6)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

"with REST" -> "by using gRPC or REST, "
</blockquote></details>

Done.
___
*[exabel/api/data/doc/access.rst, line 9 at r1](https://reviewable.io/reviews/exabel/api/61#-MdMnbMa7hbBJ195_09O:-MdMwOD084qFzk4V_6Ej:b-896fix) ([raw file](https://github.com/exabel/api/blob/7fd120140e6c61a1550e6adb219cd3a9b4b67d28/exabel/api/data/doc/access.rst#L9)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

Include full URL to Data API https://github.com/Exabel/api/tree/master/exabel/api/data/v1
</blockquote></details>

Done.
___
*[exabel/api/data/doc/access.rst, line 11 at r1](https://reviewable.io/reviews/exabel/api/61#-MdMo1ic0W7zBIMAct95:-MdMwdByAqCUITRT4W2f:b-3l7hk1) ([raw file](https://github.com/exabel/api/blob/7fd120140e6c61a1550e6adb219cd3a9b4b67d28/exabel/api/data/doc/access.rst#L11)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

"For API reference documentation of the REST API, please see <section> in this guide. Reference documentation for gRPC can be found here: …"


 Is it possible to make a supersection "REST API" (or similar) for the pages entities, relationships, signals, and timeseries?
</blockquote></details>

I was looking for a way to group these together, but I have not found any way of doing this without putting them in the same file.

**Review by oyvindwe — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/61)* status: all files reviewed, 2 unresolved discussions (waiting on @hallarak and @oyvindwe)

___
*[exabel/api/data/doc/access.rst, line 11 at r1](https://reviewable.io/reviews/exabel/api/61#-MdMo1ic0W7zBIMAct95:-MdN-z2I-An7ugbPrx0j:b7bczaq) ([raw file](https://github.com/exabel/api/blob/7fd120140e6c61a1550e6adb219cd3a9b4b67d28/exabel/api/data/doc/access.rst#L11)):*
<details><summary><i>Previously, hallarak (Øystein Hallaråker) wrote…</i></summary><blockquote>

I was looking for a way to group these together, but I have not found any way of doing this without putting them in the same file. 
</blockquote></details>

OK - just refer to "later sections in this guide" then? 
___
*[exabel/api/data/doc/access.rst, line 9 at r2](https://reviewable.io/reviews/exabel/api/61#-MdN-mk78JOEOFN0hpTo:-MdN-mk78JOEOFN0hpTp:b-rr23hn) ([raw file](https://github.com/exabel/api/blob/1335a4d3777eef1abb5fa450442dde73c474132e/exabel/api/data/doc/access.rst#L9)):*
> ```reStructuredText
> Python SDK: https://pypi.org/project/exabel-data-sdk/
> 
> The Data API service definitions can be found here: https://github.com/Exabel/api/tree/master/exabel/api/data/v1.
> ```

Remove `.` (I'm not sure how links with it will me made, but it's not included in previous paragraph)

**Review by hallarak — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/61)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @oyvindwe)

___
*[exabel/api/data/doc/access.rst, line 11 at r1](https://reviewable.io/reviews/exabel/api/61#-MdMo1ic0W7zBIMAct95:-MdQgAVN6OD1yvIctmip:bb6un1j) ([raw file](https://github.com/exabel/api/blob/7fd120140e6c61a1550e6adb219cd3a9b4b67d28/exabel/api/data/doc/access.rst#L11)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

OK - just refer to "later sections in this guide" then? 
</blockquote></details>

Done
___
*[exabel/api/data/doc/access.rst, line 9 at r2](https://reviewable.io/reviews/exabel/api/61#-MdN-mk78JOEOFN0hpTo:-MdN4jQpB6aKLv8omhZI:b-896fix) ([raw file](https://github.com/exabel/api/blob/1335a4d3777eef1abb5fa450442dde73c474132e/exabel/api/data/doc/access.rst#L9)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

Remove `.` (I'm not sure how links with it will me made, but it's not included in previous paragraph)
</blockquote></details>

Done.

**Review by oyvindwe — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/61#-:-MdWv9KB8F20tu_eqeIH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
