### PR TITLE
Group search results

### PR DESCRIPTION
**Pull request by bnordli**
This change is [Reviewable](https://reviewable.io/reviews/exabel/api/75)

### CODE REVIEW

**Comment by bnordli** [comment]
[Data API: Group search results](https://trello.com/c/eDSq2DSS/2892-data-api-group-search-results)

**Review by oyvindwe — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/75)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @bnordli)

___
*[exabel/api/data/v1/entity_service.proto, line 194 at r1](https://reviewable.io/reviews/exabel/api/75#-Mgf-BZC-z7cjc-XV8gH:-Mgf-BZC-z7cjc-XV8gI:bsrnrod) ([raw file](https://github.com/exabel/api/blob/94ae337d5e70e048f31f303693b761e23238e7e3/exabel/api/data/v1/entity_service.proto#L194)):*
> ```protobuf
>   // The results of each search, in the request order. Note that some consecutive terms are defined
>   // as belonging to one search query, and in these cases the number of results will be less than
>   // the number of search terms.
> ```

It is not completely clear how this works with search on `isin` vs. `mic` and `ticker `. Maybe put the search term(s) in the search result for context? Then the client can throw away the request and only inspect the result as well.

**Review by bnordli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/75)* status: 1 of 2 files reviewed, all discussions resolved

___
*[exabel/api/data/v1/entity_service.proto, line 194 at r1](https://reviewable.io/reviews/exabel/api/75#-Mgf-BZC-z7cjc-XV8gH:-MgjCMys57xoZCY802Us:b-isq59) ([raw file](https://github.com/exabel/api/blob/94ae337d5e70e048f31f303693b761e23238e7e3/exabel/api/data/v1/entity_service.proto#L194)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

It is not completely clear how this works with search on `isin` vs. `mic` and `ticker `. Maybe put the search term(s) in the search result for context? Then the client can throw away the request and only inspect the result as well.
</blockquote></details>

Done. (It complicated the implementation by quite a bit, but I also think it is reasonable to return them.)

**Review by oyvindwe — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/75#-:-MgjFHOu5mRvv0OPCc2D:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by oyvindwe — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/75)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[exabel/api/data/v1/entity_service.proto, line 162 at r2](https://reviewable.io/reviews/exabel/api/75#-MgjFR0jE95PtRrqtYTO:-MgjFR0jE95PtRrqtYTP:b5nfq77) ([raw file](https://github.com/exabel/api/blob/1547d0fdb30c31e144f96913015f0b8e8970b2e7/exabel/api/data/v1/entity_service.proto#L162)):*
> ```protobuf
> // A search for companies should contain either
> //   * an 'ISIN' (International Securities Identification Number) field, or
> //   * a 'MIC' (Market Identifier Code) and a 'ticker' field, or
> ```

I suggest a future improvement to group these two terms explict.

**Review by bnordli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/75)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[exabel/api/data/v1/entity_service.proto, line 162 at r2](https://reviewable.io/reviews/exabel/api/75#-MgjFR0jE95PtRrqtYTO:-MgjGiz14_lV1eCRSd5i:b-uv6y0b) ([raw file](https://github.com/exabel/api/blob/1547d0fdb30c31e144f96913015f0b8e8970b2e7/exabel/api/data/v1/entity_service.proto#L162)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

I suggest a future improvement to group these two terms explict.
</blockquote></details>

Yes, having ambiguous grouping has led to lot's of complications..

**Pull request merged**
