### PR TITLE
DEV-62: Data set service

### PR DESCRIPTION
**Pull request by bnordli**
This change is [Reviewable](https://reviewable.io/reviews/exabel/api/85)

### CODE REVIEW

**Review by oyvindwe — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/85)* status: all files reviewed, 3 unresolved discussions (waiting on @bnordli)

___
*[exabel/api/data/v1/entity_messages.proto, line 53 at r1](https://reviewable.io/reviews/exabel/api/85#-Mq-0YLc-DPDMB1npgN_:-Mq-0YLc-DPDMB1npgNa:bcljz0y) ([raw file](https://github.com/exabel/api/blob/24f2b0acbe60d66e6740c2684bbe802afa16433b/exabel/api/data/v1/entity_messages.proto#L53)):*
> ```protobuf
>   string description = 3;
>   // Output only. Whether this resource is read only.
>   bool read_only = 4;
> ```

You missed one: `[(google.api.field_behavior) = OUTPUT_ONLY];`
___
*[exabel/api/data/v1/relationship_service.proto, line 109 at r1](https://reviewable.io/reviews/exabel/api/85#-Mq-12Cc1Kv6iPE6n6iD:-Mq-12Cc1Kv6iPE6n6iE:b-vvfy68) ([raw file](https://github.com/exabel/api/blob/24f2b0acbe60d66e6740c2684bbe802afa16433b/exabel/api/data/v1/relationship_service.proto#L109)):*
> ```protobuf
> message CreateRelationshipTypeRequest {
>   // The relationship type to create.
>   RelationshipType relationship_type = 1;
> ```

Not `[(google.api.field_behavior) = REQUIRED];`? And below as well?
___
*[exabel/api/data/v1/time_series_messages.proto, line 61 at r1](https://reviewable.io/reviews/exabel/api/85#-Mq-1woP9lrdSI4iZazk:-Mq-1woP9lrdSI4iZazl:b-a36cfm) ([raw file](https://github.com/exabel/api/blob/24f2b0acbe60d66e6740c2684bbe802afa16433b/exabel/api/data/v1/time_series_messages.proto#L61)):*
> ```protobuf
>   // be treated as not set. If not set, no points will be returned. If set, but empty, all points
>   // will be returned.
>   api.time.TimeRange time_range = 1;
> ```

`[(google.api.field_behavior) = REQUIRED];`?

**Review by bnordli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/85)* status: all files reviewed, 2 unresolved discussions (waiting on @oyvindwe)

___
*[exabel/api/data/v1/entity_messages.proto, line 53 at r1](https://reviewable.io/reviews/exabel/api/85#-Mq-0YLc-DPDMB1npgN_:-Mq-2Tvx5xNh0dAdhrQe:b-ucfknh) ([raw file](https://github.com/exabel/api/blob/24f2b0acbe60d66e6740c2684bbe802afa16433b/exabel/api/data/v1/entity_messages.proto#L53)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

You missed one: `[(google.api.field_behavior) = OUTPUT_ONLY];`
</blockquote></details>

Thanks!
___
*[exabel/api/data/v1/relationship_service.proto, line 109 at r1](https://reviewable.io/reviews/exabel/api/85#-Mq-12Cc1Kv6iPE6n6iD:-Mq-2V368laa-STOIkjC:bb85osz) ([raw file](https://github.com/exabel/api/blob/24f2b0acbe60d66e6740c2684bbe802afa16433b/exabel/api/data/v1/relationship_service.proto#L109)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

Not `[(google.api.field_behavior) = REQUIRED];`? And below as well?
</blockquote></details>

This was the only service that had `Required.` notes. I think it is fairly evident that when you try to create or update something, you have to specify what those objects are. So I decided to drop these. I might be convinced otherwise, though.
___
*[exabel/api/data/v1/time_series_messages.proto, line 61 at r1](https://reviewable.io/reviews/exabel/api/85#-Mq-1woP9lrdSI4iZazk:-Mq-3MgHDm_EkiVug3_Z:b-k3bqp9) ([raw file](https://github.com/exabel/api/blob/24f2b0acbe60d66e6740c2684bbe802afa16433b/exabel/api/data/v1/time_series_messages.proto#L61)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

`[(google.api.field_behavior) = REQUIRED];`?
</blockquote></details>

"If not set, no points will be returned."

**Review by oyvindwe — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/85)* status: all files reviewed, 1 unresolved discussion (waiting on @bnordli)

___
*[exabel/api/data/v1/relationship_service.proto, line 109 at r1](https://reviewable.io/reviews/exabel/api/85#-Mq-12Cc1Kv6iPE6n6iD:-Mq-4bhi4i0s7KlVIGbF:bw0rgja) ([raw file](https://github.com/exabel/api/blob/24f2b0acbe60d66e6740c2684bbe802afa16433b/exabel/api/data/v1/relationship_service.proto#L109)):*
<details><summary><i>Previously, bnordli (Børge Nordli) wrote…</i></summary><blockquote>

This was the only service that had `Required.` notes. I think it is fairly evident that when you try to create or update something, you have to specify what those objects are. So I decided to drop these. I might be convinced otherwise, though.
</blockquote></details>

For consistency, I think we should _always_ set the annotation in the case where "failure to [provide a value] will cause an error (usually `INVALID_ARGUMENT`).", per https://github.com/googleapis/googleapis/blob/master/google/api/field_behavior.proto#L59
___
*[exabel/api/data/v1/time_series_messages.proto, line 61 at r1](https://reviewable.io/reviews/exabel/api/85#-Mq-1woP9lrdSI4iZazk:-Mq-4U8V5BgXYYdOJyBf:b-okfda) ([raw file](https://github.com/exabel/api/blob/24f2b0acbe60d66e6740c2684bbe802afa16433b/exabel/api/data/v1/time_series_messages.proto#L61)):*
<details><summary><i>Previously, bnordli (Børge Nordli) wrote…</i></summary><blockquote>

"If not set, no points will be returned."
</blockquote></details>

I agree - I was only looking at the change. No error thrown here!

**Review by bnordli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/api/85)* status: 10 of 17 files reviewed, 1 unresolved discussion (waiting on @oyvindwe)

___
*[exabel/api/data/v1/relationship_service.proto, line 109 at r1](https://reviewable.io/reviews/exabel/api/85#-Mq-12Cc1Kv6iPE6n6iD:-Mq-CsRu9DuLJEaJ6b2c:b2nhktc) ([raw file](https://github.com/exabel/api/blob/24f2b0acbe60d66e6740c2684bbe802afa16433b/exabel/api/data/v1/relationship_service.proto#L109)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

For consistency, I think we should _always_ set the annotation in the case where "failure to [provide a value] will cause an error (usually `INVALID_ARGUMENT`).", per https://github.com/googleapis/googleapis/blob/master/google/api/field_behavior.proto#L59
</blockquote></details>

OK!

**Review by oyvindwe — APPROVED** [review]
Nice to introduce the REQUIRED annotations! :lgtm: 

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/api/85#-:-Mq-Md2-07dsvw3z492F:bop4dsr)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[-- commits, line 25 at r3](https://reviewable.io/reviews/exabel/api/85#-Mq-MBal2AWoJ4bCRQku):*
Not for optional fields I hope. :-D

**Pull request merged**
